server.port=8080

# ===== Microsoft Entra ID =====
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/d682dd0f-c16d-441b-9de9-821ad928a813/v2.0
spring.security.oauth2.resourceserver.jwt.audiences[0]=9310766b-17b5-4bbc-b37c-68ff05fbf500

# ===== Base de datos MySQL (AWS RDS) =====
spring.datasource.url=${DB_URL:jdbc:mysql://pedidos360-db.c4zixrkapwdc.us-east-1.rds.amazonaws.com:3306/pedidos360?useSSL=true&serverTimezone=UTC}
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect